### ISSUE TITLE
请问后台代码有么

### ISSUE THREAD

**Issue by violet520** [hi-craft/Wechat-AccessibilityService#1]
请问后台代码有么，多谢，可以加微信么

**Comment by hi-craft** [comment]
> 请问后台代码有么，多谢，可以加微信么

后台代码找不到了，比较基础，也就几十行。
登录从客户端发送imei码，服务端查表判断是否激活
注册从客户端发送imei码和给定激活码，服务端判断是否注册，激活码是否有效
然后用pm2守护进程

**Comment by aogg** [comment]
如何关闭后台代码
